### PR TITLE
[feat] delete action for data stores

### PR DESCRIPTION
**Pull request by wol-soft**
Add the feature to delete data stores with the CLI tool. Currently deleting data stores is only possible with the API v2.

### CODE REVIEW

**Comment by robingustafsson** [comment]
Thanks for the PR @wol-soft, I'll have a look at it.

**Comment by wol-soft** [comment]
If I execute the tests locally, the test test_create_scenario_with_datastore_files which fails in Travis is OK. Instead the test test_list_datastore_missing_project_id fails what surprised me very much. But that test also fails locally on the develop branch.

**Comment by robingustafsson** [comment]
@wol-soft The tests pass on both 2.7 and 3.6 on my machine (both this PR and `develop`). Not sure why the test fails on Travis yet.

I'll merge this PR and then work from there.

Thanks for the contribution!

**Comment by robingustafsson** [comment]
Now the tests passed when merged into develop: https://travis-ci.org/loadimpact/loadimpact-cli/builds/366419172

I wonder if it has anything to do with the source of this PR being "unknown repository", where did you PR this from?

**Comment by ghost** [comment]
I forked your repository, made my changes in my local repository and then created the PR from the forked repository. Some days ago I deleted my fork, probably the PR then went to an "unknown repository" but the tests failed on Travis while my fork was still existing.

btw. @ewoortmann and @wol-soft are both my accounts, messed up a little bit ;)

**Comment by robingustafsson** [comment]
Ah ok, yeah that likely explains the "unknown repository".

Thanks again for the PR.

**Pull request merged**
